parameters:
#    xenopedia_admin.example.class: Xenopedia\AdminBundle\Example

services:
#    xenopedia_admin.example:
#        class: %xenopedia_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
