xenopedia_admin:
    resource: "@XenopediaAdminBundle/Resources/config/routing.yml"
    prefix:   /admin/

xenopedia_user:
    resource: "@XenopediaUserBundle/Resources/config/routing.yml"
    prefix:   /

xenopedia_site:
    resource: "@XenopediaSiteBundle/Resources/config/routing.yml"
    prefix:   /

    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /
    
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
 
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
 
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
 
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
