parameters:
#    xenopedia_user.example.class: Xenopedia\UserBundle\Example

services:
#    xenopedia_user.example:
#        class: %xenopedia_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    xenopedia_user_registration.form.type:
        class: Xenopedia\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: xenopedia_user_registration }