<?php

namespace Xenopedia\SiteBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ClicheController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Xenopedia\SiteBundle\Controller\ClicheController();
        return $instance;
    }
}
