<?php

namespace Xenopedia\UserBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SubmissionController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Xenopedia\UserBundle\Controller\SubmissionController();
        return $instance;
    }
}
