<?php

namespace Xenopedia\AdminBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ManagementController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Xenopedia\AdminBundle\Controller\ManagementController();
        return $instance;
    }
}
