<?php

namespace Xenopedia\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * categorieMinoriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categorieMinoriteRepository extends EntityRepository
{
}
