<?php

namespace Xenopedia\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClicheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClicheRepository extends EntityRepository
{

	public function findByVote($nbCliche)
	{
		$qb = $this->createQueryBuilder('c');
 
		$qb->orderBy('c.vote', 'DESC')
			->setMaxResults($nbCliche);
 
			return $qb->getQuery()
						->getResult();
	}
	
	public function getClicheFromAuteur($username)
	{
		$qb = $this->createQueryBuilder('c')
					->leftJoin('c.auteur', 'u')
					->addSelect('u')
					->where('u.username = :username')
					->setParameter('username',$username);
 
		return $qb->getQuery()
					->getResult();
	}
	
	public function getClicheParMinorite($minorite)
	{
				$qb = $this->createQueryBuilder('c')
					->leftJoin('c.minorite', 'm')
					->addSelect('m')
					->where('m.nom = :minorite')
					->setParameter('minorite',$minorite);
 
		return $qb->getQuery()
					->getResult();
	}
}
